version: '3'
services:
  restaurant_db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PWD}
            - POSTGRES_DB=${PG_DATABASE}
        volumes:
          - ./migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/000001_init_schema.up.sql
          - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_PWD}" ]
          interval: 30s
          timeout: 10s
          retries: 5
        networks:
          - mediasoft-task

  restaurant:
        build:
            context: .
            dockerfile: Dockerfile
        image: mediasoft-restaurant
        depends_on:
          restaurant_db:
            condition: service_healthy
        ports:
            - "8002:8002"
            - "8003:8003"
        networks:
          - mediasoft-task

networks:
  mediasoft-task:
    external: true